# Generated by Django 6.0 on 2025-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('best_time', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('quote', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
