# Generated by Django 6.0 on 2025-12-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(max_length=10000),
        ),
    ]
